### ISSUE TITLE
Security vulnerability in dependent version of marked

### ISSUE THREAD

**Issue by andy-viv** [mikaelbr/cli-usage#14]
There was a new security vulnerability found in `marked`, and a fix was put in [version 0.6.2](https://github.com/markedjs/marked/releases/tag/v0.6.2).

Could you please update to 0.6.2 and push a new release? Thanks!

**Comment by apoco** [comment]
Created a PR if it helps: https://github.com/mikaelbr/cli-usage/pull/15

From what I can tell, the breaking changes from 0.5 -> 0.6 doesn't impact this library.

**Comment by mikaelbr** [comment]
Thanks!

**Comment by mikaelbr** [comment]
Out now:

```
npm notice 📦  cli-usage@0.1.9
```
