### ISSUE TITLE
marked-terminal version 3.2.0 is not yet posted to npm?

### ISSUE THREAD

**Issue by salminio** [mikaelbr/cli-usage#16]
npm ERR! code ETARGET
npm ERR! notarget No matching version found for marked-terminal@^3.2.0
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'cli-usage'
npm ERR! notarget

**Comment by mikaelbr** [comment]
Odd. Is probably an issue with a custom registry your using or proxy/cache. 

See https://www.npmjs.com/package/marked-terminal that current version is 3.2.0 and you can check in your terminal:

```
$ npm show marked-terminal version
3.2.0
```

**Comment by salminio** [comment]
mine shows 3.1.1

**Comment by mikaelbr** [comment]
3.2.0 is published 3 months ago to the official registry. Check your end.
