### ISSUE TITLE
consider migrating from marked

### ISSUE THREAD

**Issue by jonathanong** [mikaelbr/cli-usage#2]
it's no longer maintained. some options are:
- https://www.npmjs.com/package/remark
- https://www.npmjs.com/package/markdown-it

not a big deal. only came here because i keep getting this message in my npm logs which i want to remove:

``` bash
npm WARN prefer global marked@0.3.5 should be installed with -g
```

**Comment by martijnrusschen** [comment]
Marked also contains a known vulnerability: https://srcclr.com/security/cross-site-scripting-xss-due-to/javascript/s-2309

**Comment by mikaelbr** [comment]
See https://github.com/mikaelbr/marked-terminal/issues/22#issuecomment-247871827
