### ISSUE TITLE
Update Dependency Package

### ISSUE THREAD

**Issue by sectsect** [mikaelbr/cli-usage#8]
Thanks for useful package.

I got the following warning on GitHub.

> :warning: We found potential security vulnerabilities in your dependencies.
> Some of the dependencies defined in your package-lock.json have known security vulnerabilities and should be updated.

<img width="742" alt="capture 2018-01-06 at 12 32 13" src="https://user-images.githubusercontent.com/5554826/34636135-630ed77e-f2de-11e7-8c9d-9027be91cf6f.png">

I think that it is necessary to update the "[marked](https://github.com/chjj/marked)" package.

@via https://github.com/chjj/marked/issues/997

**Comment by KiaFarhang** [comment]
Hi there! Thanks to @mikaelbr and @matildasmeds for quickly handling this issue.

A quick follow-up: It seems that the latest version of `cli-usage` on NPM still depends on the vulnerable version of `marked`. Any chance you could publish this newest version to the registry?

Thanks in advance!

**Comment by mikaelbr** [comment]
Of course. This is published now. Sorry for the delay. There'll soon be a new version (major) due to updating markdown output also.

```
+ cli-usage@0.1.7
```

**Comment by sectsect** [comment]
@mikaelbr @matildasmeds 

Thank you for your response 👍🏻
